language: node_js
node_js:
- '0.12'
branches:
  only:
  - source
script: sh build.sh
env:
  global:
    secure: Mz9OSHYKRCHfOCpZykGlvcSGcl26eWtRIj6p/ArGAAQtGqdpn4FHktwFPkx5xD2LKZm+1432lqMnXHO7XMw0fKenZnOhC+NAjjg6t1DswwfGhKqLO6emcotejuVm6v+v44JuP7RFFboE3nZwRiUomkVvBWynLz1+BPbFChIkQwV3k3orvG9kh5oWSqyJbjy6K4jSLeJQrjeK0Ap0duwqu3aWp0X87ICXPrOrOKWQFnTiCQnzTwpyyc+gYSnjkoxMJPOiHlKJ81+awQnf7tRe0K3PVeKAHODE4MMWbE58f1k7XPxPTWrMYYZOEqNYL+dGFZ5bsMF7r08FN8NGFbsL9JIiZs5u7Ti4AA2htDFhlCG9SARlLxqgQJkYXP1V3hyGQG1hbBwJQeG14UPfJV8wyy0IxuZE4SIlaA730tTuRbYkMAUUSpQXkFJLyBR0oexXjff0vQMG8R1wurG3K/C1p0eaa8l+ItCdDnRHFBOlen5HK3UHeY/Ino4rEXsjzHBhm9HwEyOoUvUz7lK6MUIRGdJPcPbigKRrPNzUbYyzSsAiA9v2UBj8oKnQQy8ChDT0q1Ln/qG+w6D6ggBO/VkXuydy8RNXA7BlnNEbed8xpsqSsmGhsVKXrwPGNN7TaP9iHQhorI+PqKhfdSVZ3yj44sI/uaIUg07wZBoe/AYefhg=
