language: node_js
node_js:
- '0.12'
branches:
  only:
  - source
script: sh build.sh
env:
  global:
    secure: TdQEvLiA1fpvbFmMuHgTv/RFix3450iP2GSNHA4kMBlmIy98OGJxyJ8swxBiSa7vcRf966mys8YNc1Zj8PjzfwzncqMVQAU7QhFddM2vVAiR1XhjHaSFPKq+RKbZ82GnyF2hKouA4J9ijiq/pK67PzG53NaHPL3ypcjFXk7RvRCiLxvDqJePuuZiKn5CsFx/PT5J0GVJUuISpsCfOBBEnYHfCEICcCZ78kBE++IvVIWOTkYxQ2H/8YytXAurmRFOHZ27tCV4+kyIIWmUqTB/15kvTJ+KLPnGpxYl4mIeBZQVVp899zQY5rqmBvrN56I1UomldriHqbGyMY6sRf8+XKvU5GNpsSjwWfnVLUjcB17upTiYthXrY5jCAkkjX6COsBRAaRyUTXGzsBTRYHICDHig8x+TT1V2UkRT3krJOvL9lttK2v+KX/hNW6hI/M4nOV00/4TIZmmqgcjd/e8nc6LT2zrThYB8p6s+Wv3AILZbD81O4cIEgyr9Xt74Cox8GAnXTxqfGFdzEXjmWd3XoRQJpsGoqg6nW9zD+yvqCpcflPAFgwY/ezSuFtjURNiYDwOHR0MfT9kvy67h939UDSzpNyFx16bdGpl7QWiWSPNDnI4e6Bq7IT1APTtJp1hZRJFoQWaeJKLjDkrIP8GD0FbBeA+o5JvZSwwEuw07alc=
