language: node_js
node_js:
- '0.12'
branches:
  only:
  - source
script: sh build.sh
env:
  global:
    secure: WUFH81dUWiHIqvGTuAFjjW2YmkAANevjBoafwyHvTxroTuw8fCPTxVOVn1ZsgW7i1pmf4ohWknnfhClV2v3+Y1R/s6b/dsrxJSC7IOa9ee6h7K/YAmx7A7Pt6/bKKREypUGBoc6+O/HQ6PJU71AbOuhbyNDxjsEdEGwBXnPuUr/YtakK1J6wrgmJCyE5ZvshLtB1V5O1H2TcDSAQv/3aFCHuTwVRQnnwDodLlQ7M0p94cNJ98LDK4ojpoflxKy8LkS8DEbOwMaA1iEYrY66obAobvw/ScP46v2LE8FalbdjwPVTiNR3mKNycEpcFMASylE0yNu/S7Gy1nLV3l3bKCdjubZOPYj9C5QR5Gj+6gxnni0SN7v0Ow9TVelGhGHherjl2Tu9DMvxe0Im3fuWJmulXUFAPbiTya1yahlAzPm55fxU6qVrYQq7es0tfSQYgw1q7QCNpgsyJXtTrCaCSJ3osm9cdViAf8LiI/PFudahyu4k/4Z3UIF5lAviRTCpXCDO7CspRyR1hjWcC5+f+sE1noV2tXI5zYt+S107jk/mOe5ZD4ZZYGHBQCuRLWsei6IvYJ5APeWqCOp8QFCa76To10RfbMu5lvPbFh76VhqkZR3K6p8CXEcs7jXO2IxVkQmF3v7jNOu0nQqas3J7UZe54MhW/k6ZGkirZrvM2NVw=
